In [2]:
import pandas as pd
import numpy as np
forecast_df = pd.read_csv(
    "../outputs/forecasts/office_supplies_12_month_forecast.csv"
)

forecast_df['Month'] = pd.to_datetime(forecast_df['Month'])
forecast_df.head()

       Month  Forecasted_Quantity
0 2015-07-01          2368.601805
1 2015-08-01          3593.319549
2 2015-09-01          4028.423440
3 2015-10-01          2652.501483
4 2015-11-01          3818.037386

In [3]:
avg_monthly_demand = forecast_df['Forecasted_Quantity'].mean()
avg_monthly_demand

np.float64(3128.940162292021)

In [4]:
historical_df = pd.read_csv("../data/processed/monthly_category_demand.csv")
office_hist = historical_df[
    historical_df['Category'] == 'Office Supplies'
]['Quantity']

demand_std = office_hist.std()
demand_std

np.float64(993.0071421682541)

In [5]:
lead_time_months = 1
service_level = 0.95      # 95% service level
z_score = 1.65            # standard for 95%

In [6]:
safety_stock = z_score * demand_std * np.sqrt(lead_time_months)
safety_stock

np.float64(1638.461784577619)

In [7]:
reorder_point = (avg_monthly_demand * lead_time_months) + safety_stock
reorder_point

np.float64(4767.40194686964)

In [8]:
inventory_policy = pd.DataFrame({
    "Metric": [
        "Average Monthly Demand",
        "Demand Std Dev",
        "Lead Time (months)",
        "Safety Stock",
        "Reorder Point"
    ],
    "Value": [
        round(avg_monthly_demand, 0),
        round(demand_std, 0),
        lead_time_months,
        round(safety_stock, 0),
        round(reorder_point, 0)
    ]
})

inventory_policy

                   Metric   Value
0  Average Monthly Demand  3129.0
1          Demand Std Dev   993.0
2      Lead Time (months)     1.0
3            Safety Stock  1638.0
4           Reorder Point  4767.0

In [9]:
inventory_policy.to_csv(
    "../outputs/inventory_policy_office_supplies.csv",
    index=False
)